baseURL: "https://blog.gyni.net/"
languageCode: "en-us"
title: "Gyni's Blog"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Gyni's Blog"
  description: "Programming & Hacking Blog"
  keywords: [Blog, Portfolio]
  author: "Gyni" # ["Me", "You"] # multiple authors
  DateFormat: "January, 2, 2006"

  hidemeta: false
  hideSummary: false

  assets:
    favicon: "/images/icons/logo-128.png"
    favicon16x16: "/images/icons/logo-16.png"
    favicon32x32: "/images/icons/logo-32.png"
    apple_touch_icon: "/images/icons/logo-64.png"
    safari_pinned_tab: "/images/icons/logo-64.png"

  label:
    text: "Gyni's Blog"

  # home-info mode
  homeInfoParams:
    Title: "Welcome to Gyni's Blog!"
    Content: "This blog is made and written by Gyni, mainly about Programming, Hacking and anything tech related."

outputs:
  home:
    - html