baseURL: "https://gyni.net/"
title: "Gyni"

buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Gyni"
  description: "Programming & Hacking Blog"
  keywords: [Blog, Portfolio]
  author: "Gyni" # ["Me", "You"] # multiple authors
  DateFormat: "January, 2, 2006"

  assets:
    logo: "/favicon-128x128.png"
    favicon: "/favicon-128x128.png"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/favicon-64x64.png"
    safari_pinned_tab: "/favicon-64x64.png"

  label:
    text: "Gyni"

  # home-info mode
  homeInfoParams:
    Title: "Welcome!"

services:
  googleAnalytics:
    id: "G-XXXXXXXXXX" # Google Analytics ID
  disqus:
    shortname: "gyni" # Disqus shortname for comments

outputs:
  home:
    - html