name = "papermod"
license = "MIT"
description = "papermod modified theme"
tags = ["blog"]
min_version = "0.83.0"

authors = [
  { name = "Ali Abdelkarim", email = "ali@gyni.net" },
]

# NOTE: this theme is from hugo-PaperMod, i've modified it for my own needs and you can get the orignal theme from: https://github.com/adityatelange/hugo-PaperMod/
